<script src="${ctx}/common/js/jquery-1.7.2.min.js"></script>
<script src="${ctx}/common/js/jquery.form.min.js"></script>
<script src="${ctx}/common/js/grid.locale-cn.js"></script>
<script src="${ctx}/common/js/jquery.jqGrid.src.js"></script>
<script src="${ctx}/common/js/hlicPlugins/hlicweb/hlicweb.js"></script>
<script src="${ctx}/common/js/hlicGridPlus.js"></script>
<script src="${ctx}/common/js/hlicStoGrid.js"></script>
<script src="${ctx}/common/js/hlicDctGrid.js"></script>
<script src="${ctx}/common/js/jquery-ui-1.10.4.custom.min.js"></script>
<script src="${ctx}/common/js/jquery.easyui.min.js"></script>
<script src="${ctx}/common/js/hlicPlugins/hlicComSelect/hlicComSelect.js"></script>
<script src="${ctx}/common/js/calendar/jquery.ui.datepicker-zh-CN.js"></script>
<script src="${ctx}/common/js/calendar/jquery.ui.datepicker.js"></script>
<script src="${ctx}/common/js/calendar/WdatePicker.js"></script>
<script src="${ctx}/common/js/hlicPlugins/hlicSelect/select2/select2.js"></script>
<script src="${ctx}/common/js/hlicPlugins/hlicSelect/hlicSelect.js"></script>
<script src="${ctx}/common/js/hlicPlugins/alertBox/hlicalertDialog.js"></script>
<script type="text/javascript">
	var sys_ctx= "${ctx}"; // 项目路径变量
</script>
